version: '3'

services:
###> doctrine/doctrine-bundle ###
  db:
    image: mysql:5.7
    container_name: shopping-cart
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shpping_cart
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: dbUser
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: